version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: price_generator_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # 日本語対応とタイムゾーン設定
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      TZ: 'Asia/Tokyo'
    volumes:
      # DBデータの永続化
      - ./data:/var/lib/postgresql/data
      # 初期化用SQLスクリプトのマウント
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: always

volumes:
  data: